### PR TITLE
Mostly Visual Formatting Changes

### PR DESCRIPTION
**Pull request by hyphena**
Fixed some spelling and grammar errors (awnser ==> answer)
Formatted questions for easier reading (horizontal lines between questions, spacing in questions, etc.)
Correct answer displayed when answered incorrectly (correct answer was A/B/C/D)

### CODE REVIEW

**Review by pikap1 — CHANGES_REQUESTED** [review]
The last pull request already fixed the Grammar errors, but I'm interested in the bug you found, can you please mark me where the error was exactly, I can't find it

**Comment by hyphena** [comment]
I don't remember fixing any bugs in the code, I only appended the correct answer when you answer a question incorrectly. There was no way of knowing which answer was the correct one after answering before.

**Comment by pikap1** [comment]
> I don't remember fixing any bugs in the code, I only appended the correct answer when you answer a question incorrectly. There was no way of knowing which answer was the correct one after answering before.

sorry, can you please make it compatible with the new code syntax?

**Comment by hyphena** [comment]
I've synced up the current files on this repo to the ones on my forked repo and made all of my changes to that version instead. The syntax should be good now, but I'm still wrapping my head around GitHub and have no clue how to use that file for this pull request.

**Pull request closed without merging**
